apiVersion: v1
kind: Namespace
metadata:
  name: alb-test-infra
---

# NOTE: 서비스는 'app' 레이블이 'nginx-v1'인 Pod들을 선택함.
apiVersion: v1
kind: Service
metadata:
  name: nginx-v1-svc
  namespace: alb-test-infra
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx-v1
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-v1-deployment
  namespace: alb-test-infra
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-v1
  template:
    metadata:
      labels:
        app: nginx-v1
    spec:
      containers:
        - name: nginx-v1
          image: dustinacr012.azurecr.io/aks02:v02
          ports:
            - containerPort: 80