apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod1
spec:
  containers:
  - name: ubuntu1
    image: ubuntu
    command: ["/bin/sh", "-c", "sleep infinity"]
  nodeSelector:
    agentpool: nodepool1

---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod2
spec:
  containers:
  - name: ubuntu2
    image: ubuntu
    command: ["/bin/sh", "-c", "sleep infinity"]
  nodeSelector:
    agentpool: nodepool02

---

apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod3
spec:
  containers:
  - name: ubuntu3
    image: ubuntu
    command: ["/bin/sh", "-c", "sleep infinity"]
  nodeSelector:
    agentpool: nodepool03